AcquisitionFrameRate: High
AcquisitionFrameRateAbs: '0'
AcquisitionFrameRateEnable: 'False'
AcquisitionFrameSendConfig: '0'
AcquisitionMode: Continuous
AutoExposureTarget: '100'
BGain: '140'
ColorTemperatureAutoSel: 'False'
ColorTemperatureIndex: Custom
Contrast: '100'
Device: ''
DeviceUserID: MV-1000RC-GE
ExposureAuto: 'Off'
ExposureTime: '40000.0'
ExtTrigJitterTime: '0'
GGain: '100'
GPOut0: '1'
GPOut1: '1'
GPOut2: '1'
GPOut3: '1'
Gain: '8.0'
Gamma: '100'
Gev SCPS Packet Size: '1976'
GevCCP: ExclusiveAccess
GevCurrentIPConfigurationPersistentIP: 'True'
GevGVCPHeartbeatDisable: 'False'
GevHeartbeatTimeout: '10000'
GevPersistentDefaultGateway: '0'
GevPersistentIPAddress: '3232243471'
GevPersistentSubnetMask: '4294967040'
GevPrimaryApplicationIPAddress: '3232243496'
GevPrimaryApplicationSocket: '50212'
GevSCDA: '3232243496'
GevSCPD: '0'
GevSCPHostPort: '50213'
GevSCSP: '3959'
Height: '2764'
In0Mod: TriggerInput
OffsetX: '0'
OffsetY: '0'
Out0Mod: StrobeOutput
Out1Mod: GPOutput
Out2Mod: GPOutput
Out3Mod: GPOutput
PixelFormat: BayerGR8
RGain: '139'
ResolutionMod: Normal
ResolutionPresetSel: Custom
ReverseX: 'False'
ReverseY: 'False'
Saturation: '120'
StrobeDelay: '0'
StrobeMode: Auto
StrobeWidth: '0'
TLParamsLocked: '0'
TriggerActivation: FallingEdge
TriggerCount: '1'
TriggerDelay: '0'
TriggerInterval: '0'
TriggerMode: 'Off'
TriggerSource: Line1
TriggerStartDelay: '0'
UserSetDefault: Default
UserSetSelector: Default
Width: '3856'
